export * from './activityLogs.service';
import { ActivityLogsService } from './activityLogs.service';
export * from './customerJobs.service';
import { CustomerJobsService } from './customerJobs.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './demo.service';
import { DemoService } from './demo.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './drivers.service';
import { DriversService } from './drivers.service';
export * from './jobTemplates.service';
import { JobTemplatesService } from './jobTemplates.service';
export * from './jobs.service';
import { JobsService } from './jobs.service';
export * from './location.service';
import { LocationService } from './location.service';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './ping.service';
import { PingService } from './ping.service';
export * from './pricing.service';
import { PricingService } from './pricing.service';
export * from './recurringJobs.service';
import { RecurringJobsService } from './recurringJobs.service';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './roles.service';
import { RolesService } from './roles.service';
export * from './stripeWebhook.service';
import { StripeWebhookService } from './stripeWebhook.service';
export * from './userInfo.service';
import { UserInfoService } from './userInfo.service';
export * from './users.service';
import { UsersService } from './users.service';
export * from './vehicles.service';
import { VehiclesService } from './vehicles.service';
export const APIS = [ActivityLogsService, CustomerJobsService, CustomersService, DemoService, DocumentsService, DriversService, JobTemplatesService, JobsService, LocationService, NotificationsService, PaymentsService, PingService, PricingService, RecurringJobsService, ReviewsService, RolesService, StripeWebhookService, UserInfoService, UsersService, VehiclesService];
