/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityLog } from './activityLog';


export interface ActivityLogResponse { 
    logs?: Array<ActivityLog> | null;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    totalPages?: number;
}

