/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogsByDayItem } from './logsByDayItem';


export interface ActivityStatistics { 
    totalLogs?: number;
    logsByAction?: { [key: string]: number; } | null;
    logsByUser?: { [key: string]: number; } | null;
    logsBySeverity?: { [key: string]: number; } | null;
    logsByDay?: Array<LogsByDayItem> | null;
}

