/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationUser } from './application-user';


export interface ActivityLog { 
    id?: string | null;
    userId: string;
    userName: string;
    userEmail: string;
    action: string;
    entityType: string;
    entityId?: string | null;
    entityName?: string | null;
    description: string;
    ipAddress?: string | null;
    userAgent?: string | null;
    /**
     * JSON string for additional metadata
     */
    metadataJson?: string | null;
    metadata?: { [key: string]: any; } | null;
    timestamp: string;
    severity: string;
    user?: ApplicationUser;
}

