/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Book job request (customer provides job details)
 */
export interface BookJobDto { 
    jobType: string | null;
    vehicleTypeRequired?: string | null;
    priority?: string | null;
    scheduledDate: string;
    scheduledTime: string | null;
    estimatedDuration?: number | null;
    customerPhone: string | null;
    customerEmail?: string | null;
    pickupLocation: string | null;
    pickupLatitude?: number | null;
    pickupLongitude?: number | null;
    deliveryLocation: string | null;
    deliveryLatitude?: number | null;
    deliveryLongitude?: number | null;
    distance?: number | null;
    items?: Array<any> | null;
    specialInstructions?: string | null;
}

