/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BroadcastNotificationDto { 
    role: string | null;
    title: string | null;
    message: string | null;
    type: string | null;
    category?: string | null;
    priority?: string | null;
    sendEmail?: boolean;
    sendPush?: boolean;
    expiresAt?: string | null;
}

