/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BulkJobRequestItem { 
    customerName?: string | null;
    customerEmail?: string | null;
    customerPhone?: string | null;
    jobType: string | null;
    vehicleTypeRequired?: string | null;
    priority?: string | null;
    scheduledDate: string;
    scheduledTime: string | null;
    estimatedDuration?: number | null;
    pickupLocation: string | null;
    deliveryLocation: string | null;
    distance?: number | null;
    items?: Array<any> | null;
    specialInstructions?: string | null;
    customerNotes?: string | null;
}

