/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ChangePasswordDto { 
    /**
     * Current password for verification
     */
    currentPassword: string | null;
    /**
     * New password to set
     */
    newPassword: string | null;
}

