/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClaimInfo } from './claim-info';


export interface ClaimsResponse { 
    userName?: string | null;
    isAuthenticated?: boolean;
    authenticationType?: string | null;
    claims?: Array<ClaimInfo> | null;
    timestamp?: string;
}

