/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePaymentDto { 
    customerId?: string | null;
    driverId?: string | null;
    jobId?: string | null;
    amount: number;
    tipAmount?: number | null;
    currency?: string | null;
    paymentMethod: string | null;
    paymentMethodDetails?: string | null;
    description?: string | null;
    notes?: string | null;
    metadata?: any | null;
}

