/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateDriverDto { 
    userId: string | null;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    phone: string | null;
    licenseNumber: string | null;
    licenseExpiry?: string;
    vehicleType?: string | null;
    vehicleRegistration?: string | null;
    status?: string | null;
    address?: string | null;
    emergencyContact?: string | null;
}

