/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateJobDto { 
    customerName: string;
    customerPhone: string;
    customerEmail: string;
    jobType: string;
    vehicleTypeRequired?: string | null;
    priority: string;
    scheduledDate: string;
    scheduledTime: string;
    estimatedDuration?: number;
    pickupLocation: string;
    deliveryLocation: string;
    distance?: number | null;
    items: string;
    specialInstructions?: string | null;
    internalNotes?: string | null;
    driverId?: string | null;
}

