/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateReviewDto { 
    jobId: string;
    rating: number;
    comment?: string | null;
    punctualityRating?: number | null;
    professionalismRating?: number | null;
    careOfItemsRating?: number | null;
    communicationRating?: number | null;
}

