/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateActivityLogRequest { 
    action?: string | null;
    entityType?: string | null;
    entityId?: string | null;
    entityName?: string | null;
    description?: string | null;
    metadata?: { [key: string]: any; } | null;
    severity?: string | null;
}

