/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateJobStopDto { 
    stopOrder: number;
    stopType: string | null;
    location: string | null;
    latitude?: number | null;
    longitude?: number | null;
    contactName?: string | null;
    contactPhone?: string | null;
    specialInstructions?: string | null;
    items?: Array<any> | null;
    scheduledArrival?: string | null;
}

