/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentDriverInfo } from './documentDriverInfo';


/**
 * View model for document response
 */
export interface DocumentViewModel { 
    id?: string;
    driverId?: string;
    type?: string | null;
    fileName?: string | null;
    fileUrl?: string | null;
    expiryDate?: string | null;
    status?: string | null;
    verifiedBy?: string | null;
    verifiedDate?: string | null;
    uploadedDate?: string;
    driver?: DocumentDriverInfo;
}

