/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * View model for document statistics
 */
export interface DocumentStatisticsViewModel { 
    totalDocuments?: number;
    pendingVerification?: number;
    verified?: number;
    rejected?: number;
    expired?: number;
    expiringSoon?: number;
    documentsByType?: { [key: string]: number; } | null;
}

