/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * View model for driver location with driver info
 */
export interface DriverLocationViewModel { 
    driverId?: string;
    driverName?: string | null;
    latitude?: number;
    longitude?: number;
    speed?: number | null;
    heading?: number | null;
    address?: string | null;
    timestamp?: string;
    ageInSeconds?: number;
}

