/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReviewDto } from './review-dto';


export interface DriverRatingSummaryDto { 
    driverId?: string;
    driverName?: string | null;
    averageRating?: number;
    totalReviews?: number;
    averagePunctualityRating?: number | null;
    averageProfessionalismRating?: number | null;
    averageCareOfItemsRating?: number | null;
    averageCommunicationRating?: number | null;
    fiveStarCount?: number;
    fourStarCount?: number;
    threeStarCount?: number;
    twoStarCount?: number;
    oneStarCount?: number;
    recentReviews?: Array<ReviewDto> | null;
}

