/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DriverDto { 
    id?: string;
    userId: string | null;
    firstName: string | null;
    lastName: string | null;
    email: string | null;
    phone: string | null;
    licenseNumber: string | null;
    licenseExpiry?: string;
    vehicleType?: string | null;
    vehicleRegistration?: string | null;
    status: string | null;
    rating?: number;
    totalJobs?: number;
    completedJobs?: number;
    activeJobs?: number;
    joinedDate?: string;
    lastActiveDate?: string | null;
    profileImage?: string | null;
    address?: string | null;
    emergencyContact?: string | null;
}

