/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DriverStatsDto { 
    todayJobs?: number;
    weekJobs?: number;
    pending?: number;
    completed?: number;
    total?: number;
    rating?: number;
}

