/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverDocument } from './driverDocument';
import { Vehicle } from './vehicle';
import { Job } from './job';


export interface Driver { 
    id?: string;
    userId: string;
    firstName: string;
    lastName: string;
    email: string;
    phone: string;
    licenseNumber: string;
    licenseExpiry: string;
    vehicleType?: string | null;
    vehicleRegistration?: string | null;
    status: string;
    rating?: number;
    totalJobs?: number;
    completedJobs?: number;
    activeJobs?: number;
    joinedDate?: string;
    lastActiveDate?: string | null;
    profileImage?: string | null;
    address?: string | null;
    emergencyContact?: string | null;
    availabilitySchedule?: string | null;
    createdAt?: string;
    updatedAt?: string;
    jobs?: Array<Job> | null;
    documents?: Array<DriverDocument> | null;
    vehicles?: Array<Vehicle> | null;
}

