/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EarningsDto { 
    totalEarnings?: number;
    totalTips?: number;
    totalJobs?: number;
    averageEarningsPerJob?: number;
    periodStart?: string | null;
    periodEnd?: string | null;
}

