/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface EarningDto { 
    id?: string;
    driverId?: string;
    jobId?: string;
    jobNumber?: string | null;
    baseAmount?: number;
    bonusAmount?: number | null;
    tipAmount?: number | null;
    deductionAmount?: number | null;
    netAmount?: number;
    paymentStatus?: string | null;
    paymentMethod?: string | null;
    paymentReference?: string | null;
    paymentDate?: string | null;
    paymentProcessedDate?: string | null;
    jobCompletedDate?: string;
    jobDistance?: number | null;
    jobDuration?: number | null;
    notes?: string | null;
    paymentDetails?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

