/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * View model for ETA calculation result
 */
export interface EtaViewModel { 
    jobId?: string;
    driverId?: string;
    driverName?: string | null;
    currentLatitude?: number;
    currentLongitude?: number;
    destinationLatitude?: number;
    destinationLongitude?: number;
    destinationAddress?: string | null;
    distanceInMiles?: number;
    durationInMinutes?: number;
    estimatedArrivalTime?: string;
    durationText?: string | null;
    distanceText?: string | null;
}

