/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GenerateJobsResponse { 
    jobsCreated?: number;
    recurringJobsProcessed?: number;
    errors?: Array<string> | null;
}

