/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Driver } from './driver';


export interface Job { 
    id?: string;
    jobNumber: string;
    customerId: string;
    customerName: string;
    customerPhone: string;
    customerEmail: string;
    driverId?: string | null;
    driver?: Driver;
    driverName?: string | null;
    jobType: string;
    vehicleTypeRequired?: string | null;
    status: string;
    priority: string;
    scheduledDate: string;
    scheduledTime: string;
    estimatedDuration?: number;
    actualStartTime?: string | null;
    actualEndTime?: string | null;
    pickupLocation: string;
    deliveryLocation: string;
    distance?: number | null;
    items: string;
    specialInstructions?: string | null;
    internalNotes?: string | null;
    customerNotes?: string | null;
    photos?: string | null;
    statusHistory: string;
    payment?: string | null;
    createdAt?: string;
    updatedAt?: string;
    completedAt?: string | null;
}

