/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Job } from './job';


/**
 * Represents a stop/location in a multi-stop delivery job
 */
export interface JobStop { 
    id?: string;
    jobId: string;
    stopOrder: number;
    stopType: string;
    location: string;
    latitude?: number | null;
    longitude?: number | null;
    contactName?: string | null;
    contactPhone?: string | null;
    specialInstructions?: string | null;
    items?: string | null;
    scheduledArrival?: string | null;
    actualArrival?: string | null;
    actualDeparture?: string | null;
    status: string;
    photos?: string | null;
    signature?: string | null;
    notes?: string | null;
    createdAt?: string;
    updatedAt?: string;
    job?: Job;
}

