/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Represents a reusable job template for repeat customers
 */
export interface JobTemplate { 
    id?: string;
    customerId: string;
    templateName: string;
    description?: string | null;
    jobType: string;
    vehicleTypeRequired?: string | null;
    priority?: string | null;
    pickupLocation: string;
    pickupLatitude?: number | null;
    pickupLongitude?: number | null;
    deliveryLocation: string;
    deliveryLatitude?: number | null;
    deliveryLongitude?: number | null;
    estimatedDistance?: number | null;
    estimatedDuration?: number | null;
    items?: string | null;
    specialInstructions?: string | null;
    customerNotes?: string | null;
    stopsConfiguration?: string | null;
    basePrice?: number | null;
    timesUsed?: number;
    lastUsedDate?: string | null;
    tags?: string | null;
    status: string;
    isDefault?: boolean;
    isShared?: boolean;
    createdAt?: string;
    updatedAt?: string;
}

