/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model for locking user account
 */
export interface LockUserModel { 
    lockoutDurationMinutes?: number | null;
    reason?: string | null;
}

