/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model for logging vehicle maintenance
 */
export interface LogMaintenanceModel { 
    maintenanceDate?: string | null;
    nextInspectionDue?: string | null;
    mileage?: number | null;
    description?: string | null;
}

