/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * View model for vehicle maintenance history
 */
export interface MaintenanceHistoryViewModel { 
    timestamp?: string;
    description?: string | null;
    userName?: string | null;
}

