/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User notification preferences
 */
export interface NotificationPreferences { 
    id?: string;
    userId: string;
    emailEnabled?: boolean;
    smsEnabled?: boolean;
    pushEnabled?: boolean;
    jobAssignedEmail?: boolean;
    jobAssignedSms?: boolean;
    jobAssignedPush?: boolean;
    jobCompletedEmail?: boolean;
    jobCompletedSms?: boolean;
    jobCompletedPush?: boolean;
    jobCancelledEmail?: boolean;
    jobCancelledSms?: boolean;
    jobCancelledPush?: boolean;
    jobRescheduledEmail?: boolean;
    jobRescheduledSms?: boolean;
    jobRescheduledPush?: boolean;
    paymentReceivedEmail?: boolean;
    paymentReceivedSms?: boolean;
    paymentReceivedPush?: boolean;
    payoutProcessedEmail?: boolean;
    payoutProcessedSms?: boolean;
    payoutProcessedPush?: boolean;
    refundProcessedEmail?: boolean;
    refundProcessedSms?: boolean;
    refundProcessedPush?: boolean;
    reviewReceivedEmail?: boolean;
    reviewReceivedSms?: boolean;
    reviewReceivedPush?: boolean;
    reviewResponseEmail?: boolean;
    reviewResponseSms?: boolean;
    reviewResponsePush?: boolean;
    systemAlertsEmail?: boolean;
    systemAlertsSms?: boolean;
    systemAlertsPush?: boolean;
    accountUpdatesEmail?: boolean;
    accountUpdatesSms?: boolean;
    accountUpdatesPush?: boolean;
    promotionalEmail?: boolean;
    promotionalSms?: boolean;
    promotionalPush?: boolean;
    enableQuietHours?: boolean;
    quietHoursStart?: string | null;
    quietHoursEnd?: string | null;
    enableEmailDigest?: boolean;
    digestFrequency?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

