/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface NotificationStatistics { 
    totalNotifications?: number;
    unreadNotifications?: number;
    readNotifications?: number;
    last24Hours?: number;
    byType?: { [key: string]: number; } | null;
    byPriority?: { [key: string]: number; } | null;
    emailsSent?: number;
    pushNotificationsSent?: number;
}

