/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentStatistics { 
    totalPayments?: number;
    totalRevenue?: number;
    totalPlatformFees?: number;
    totalDriverEarnings?: number;
    totalTips?: number;
    totalRefunds?: number;
    pendingPayments?: number;
    completedPayments?: number;
    failedPayments?: number;
    refundedPayments?: number;
    averagePaymentAmount?: number;
    paymentsByMethod?: { [key: string]: number; } | null;
}

