/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Driver } from './driver';
import { Job } from './job';


export interface Payment { 
    id?: string;
    paymentNumber: string;
    customerId: string;
    customerName: string;
    customerEmail: string;
    driverId?: string | null;
    driver?: Driver;
    driverName?: string | null;
    jobId?: string | null;
    job?: Job;
    jobNumber?: string | null;
    amount: number;
    tipAmount?: number | null;
    platformFee?: number;
    driverEarnings?: number;
    refundAmount?: number | null;
    totalAmount: number;
    currency: string;
    paymentMethod: string;
    paymentMethodDetails?: string | null;
    status: string;
    stripePaymentIntentId?: string | null;
    stripeChargeId?: string | null;
    stripeRefundId?: string | null;
    paidAt?: string | null;
    refundedAt?: string | null;
    payoutProcessedAt?: string | null;
    description?: string | null;
    notes?: string | null;
    failureCode?: string | null;
    failureMessage?: string | null;
    metadata?: string | null;
    receiptUrl?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

