/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentStatusSummaryDto { 
    pendingCount?: number;
    pendingAmount?: number;
    processingCount?: number;
    processingAmount?: number;
    paidCount?: number;
    paidAmount?: number;
    failedCount?: number;
    failedAmount?: number;
}

