/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Driver } from './driver';


export interface Payout { 
    id?: string;
    payoutNumber: string;
    driverId: string;
    driver?: Driver;
    driverName: string;
    amount: number;
    currency: string;
    status: string;
    paymentMethod: string;
    bankAccountDetails?: string | null;
    stripePayoutId?: string | null;
    stripeAccountId?: string | null;
    periodStart?: string;
    periodEnd?: string;
    paymentIds?: string | null;
    totalJobs?: number;
    processedAt?: string | null;
    paidAt?: string | null;
    failedAt?: string | null;
    failureReason?: string | null;
    notes?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

