/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Ping response model
 */
export interface PingResponse { 
    /**
     * Indicates if the service is operational
     */
    ok?: boolean;
    /**
     * Current UTC timestamp
     */
    time?: string;
    /**
     * Status message
     */
    message?: string | null;
    /**
     * Authenticated user (if applicable)
     */
    user?: string | null;
}

