/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pricing breakdown details
 */
export interface PricingBreakdownDto { 
    baseFare?: number;
    distanceCharge?: number;
    timeCharge?: number;
    vehicleTypeCharge?: number;
    surgeMultiplier?: number;
    totalPrice?: number;
}

