/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Request to calculate pricing for a job
 */
export interface PricingCalculationRequest { 
    pickupAddress: string | null;
    deliveryAddress: string | null;
    vehicleType: string | null;
    scheduledDate?: string;
    serviceAddons?: Array<string> | null;
    numberOfHelpers?: number | null;
    distanceInMiles?: number | null;
    estimatedDurationMinutes?: number | null;
}

