/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Pricing rule entity for configurable pricing
 */
export interface PricingRule { 
    id?: string;
    name: string;
    description?: string | null;
    type: string;
    vehicleType?: string | null;
    minDistance?: number | null;
    maxDistance?: number | null;
    startTime?: string | null;
    endTime?: string | null;
    weekendOnly?: boolean | null;
    weekdayOnly?: boolean | null;
    fixedAmount?: number | null;
    perMileRate?: number | null;
    perMinuteRate?: number | null;
    multiplierPercentage?: number | null;
    serviceAddonType?: string | null;
    priority?: number;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string;
    createdBy?: string | null;
}

