/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Individual item in price breakdown
 */
export interface PriceBreakdownItem { 
    description: string | null;
    amount?: number;
    details?: string | null;
}

