/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProfilePictureResponseDto { 
    /**
     * Success message
     */
    message?: string | null;
    /**
     * URL of the uploaded profile picture
     */
    url?: string | null;
    /**
     * File name of the uploaded picture
     */
    fileName?: string | null;
}

