/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefundResponseDto { 
    paymentId?: string;
    paymentNumber?: string | null;
    refundAmount?: number;
    originalAmount?: number;
    refundStatus?: string | null;
    reason?: string | null;
    refundedAt?: string;
    refundReference?: string | null;
}

