/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Job } from './job';


export interface Review { 
    id?: string;
    reviewerId: string;
    reviewerName: string;
    reviewerType: string;
    revieweeId: string;
    revieweeName: string;
    revieweeType: string;
    jobId?: string | null;
    job?: Job;
    rating: number;
    comment: string;
    photos?: string | null;
    response?: string | null;
    responseDate?: string | null;
    respondedBy?: string | null;
    status?: string | null;
    isFlagged?: boolean;
    flagReason?: string | null;
    flaggedBy?: string | null;
    flaggedDate?: string | null;
    moderatorNotes?: string | null;
    isHidden?: boolean;
    moderatedBy?: string | null;
    moderatedDate?: string | null;
    createdAt?: string;
    updatedAt?: string;
}

