/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReviewDto { 
    id?: string;
    jobId?: string;
    jobNumber?: string | null;
    driverId?: string;
    driverName?: string | null;
    customerEmail?: string | null;
    customerName?: string | null;
    rating?: number;
    comment?: string | null;
    punctualityRating?: number | null;
    professionalismRating?: number | null;
    careOfItemsRating?: number | null;
    communicationRating?: number | null;
    status?: string | null;
    driverResponse?: string | null;
    responseDate?: string | null;
    helpfulVotes?: number;
    createdAt?: string;
    updatedAt?: string;
}

