/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SendNotificationDto { 
    userId: string | null;
    title: string | null;
    message: string | null;
    type: string | null;
    category?: string | null;
    entityType?: string | null;
    entityId?: string | null;
    actionUrl?: string | null;
    actionText?: string | null;
    data?: any | null;
    priority?: string | null;
    sendEmail?: boolean;
    sendPush?: boolean;
    expiresAt?: string | null;
}

