/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateRecurringJobDto { 
    name?: string | null;
    description?: string | null;
    items?: Array<any> | null;
    specialInstructions?: string | null;
    preferredTime?: string | null;
    endDate?: string | null;
    occurrenceCount?: number | null;
}

