/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateJobDto { 
    customerName?: string | null;
    customerPhone?: string | null;
    customerEmail?: string | null;
    jobType?: string | null;
    vehicleTypeRequired?: string | null;
    priority?: string | null;
    status?: string | null;
    scheduledDate?: string | null;
    scheduledTime?: string | null;
    estimatedDuration?: number | null;
    pickupLocation?: string | null;
    deliveryLocation?: string | null;
    distance?: number | null;
    items?: string | null;
    specialInstructions?: string | null;
    internalNotes?: string | null;
    customerNotes?: string | null;
}

