/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateJobTemplateDto { 
    templateName?: string | null;
    description?: string | null;
    jobType?: string | null;
    vehicleTypeRequired?: string | null;
    priority?: string | null;
    pickupLocation?: string | null;
    pickupLatitude?: number | null;
    pickupLongitude?: number | null;
    deliveryLocation?: string | null;
    deliveryLatitude?: number | null;
    deliveryLongitude?: number | null;
    estimatedDistance?: number | null;
    estimatedDuration?: number | null;
    items?: Array<any> | null;
    specialInstructions?: string | null;
    customerNotes?: string | null;
    stops?: Array<any> | null;
    basePrice?: number | null;
    tags?: Array<string> | null;
    isDefault?: boolean | null;
}

