/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateNotificationPreferencesDto { 
    emailEnabled?: boolean | null;
    smsEnabled?: boolean | null;
    pushEnabled?: boolean | null;
    jobAssignedEmail?: boolean | null;
    jobAssignedSms?: boolean | null;
    jobAssignedPush?: boolean | null;
    jobCompletedEmail?: boolean | null;
    jobCompletedSms?: boolean | null;
    jobCompletedPush?: boolean | null;
    jobCancelledEmail?: boolean | null;
    jobCancelledSms?: boolean | null;
    jobCancelledPush?: boolean | null;
    jobRescheduledEmail?: boolean | null;
    jobRescheduledSms?: boolean | null;
    jobRescheduledPush?: boolean | null;
    paymentReceivedEmail?: boolean | null;
    paymentReceivedSms?: boolean | null;
    paymentReceivedPush?: boolean | null;
    payoutProcessedEmail?: boolean | null;
    payoutProcessedSms?: boolean | null;
    payoutProcessedPush?: boolean | null;
    reviewReceivedEmail?: boolean | null;
    reviewReceivedSms?: boolean | null;
    reviewReceivedPush?: boolean | null;
    systemAlertsEmail?: boolean | null;
    systemAlertsSms?: boolean | null;
    systemAlertsPush?: boolean | null;
    promotionalEmail?: boolean | null;
    promotionalSms?: boolean | null;
    promotionalPush?: boolean | null;
    enableQuietHours?: boolean | null;
    quietHoursStart?: string | null;
    quietHoursEnd?: string | null;
    enableEmailDigest?: boolean | null;
    digestFrequency?: string | null;
}

