/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Model for updating user information
 */
export interface UpdateUserModel { 
    email?: string | null;
    userName?: string | null;
    phoneNumber?: string | null;
    emailConfirmed?: boolean | null;
    phoneNumberConfirmed?: boolean | null;
    roles?: Array<string> | null;
}

