/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateVehicleDto { 
    type?: string | null;
    make?: string | null;
    model?: string | null;
    year?: number | null;
    registrationNumber?: string | null;
    vinNumber?: string | null;
    cargoCapacity?: number | null;
    maxPayloadWeight?: number | null;
    maxGrossWeight?: number | null;
    cargoLength?: number | null;
    cargoWidth?: number | null;
    cargoHeight?: number | null;
    features?: string | null;
    hasInsurance?: boolean | null;
    insuranceExpiry?: string | null;
    status?: string | null;
    lastInspectionDate?: string | null;
    nextInspectionDue?: string | null;
    mileage?: number | null;
    photos?: string | null;
    isActive?: boolean | null;
}

