/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserClaimViewModel } from './userClaimViewModel';


/**
 * View model for user response
 */
export interface UserViewModel { 
    id?: string | null;
    email?: string | null;
    userName?: string | null;
    emailConfirmed?: boolean;
    phoneNumber?: string | null;
    phoneNumberConfirmed?: boolean;
    roles?: Array<string> | null;
    lockoutEnabled?: boolean;
    lockoutEnd?: string | null;
    twoFactorEnabled?: boolean;
    claims?: Array<UserClaimViewModel> | null;
}

