/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * View model for user claim
 */
export interface UserClaimViewModel { 
    type?: string | null;
    value?: string | null;
}

