/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserViewModel } from './userViewModel';


/**
 * View model for paginated user list
 */
export interface UserListViewModel { 
    users?: Array<UserViewModel> | null;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    readonly totalPages?: number;
}

