/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VehicleViewModel } from './vehicleViewModel';


/**
 * View model for paginated vehicle list
 */
export interface VehicleListViewModel { 
    vehicles?: Array<VehicleViewModel> | null;
    totalCount?: number;
    page?: number;
    pageSize?: number;
    readonly totalPages?: number;
}

