/**
 * BeC API
 *
 * Contact: bchelinje@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DriverInfo } from './driverInfo';


/**
 * View model for vehicle response
 */
export interface VehicleViewModel { 
    id?: string;
    driverId?: string;
    type?: string | null;
    make?: string | null;
    model?: string | null;
    year?: number;
    registrationNumber?: string | null;
    vinNumber?: string | null;
    cargoCapacity?: number;
    maxPayloadWeight?: number;
    maxGrossWeight?: number;
    cargoLength?: number | null;
    cargoWidth?: number | null;
    cargoHeight?: number | null;
    features?: Array<string> | null;
    hasInsurance?: boolean;
    insuranceExpiry?: string | null;
    status?: string | null;
    lastInspectionDate?: string | null;
    nextInspectionDue?: string | null;
    mileage?: number | null;
    photos?: Array<string> | null;
    isActive?: boolean;
    createdAt?: string;
    updatedAt?: string | null;
    driver?: DriverInfo;
}

